function train = import_train(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TRAIN = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  TRAIN = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  train = importfile("/Users/madeleinvillegas/Documents/MATLAB/lboec3alboec3blboec3c-project-2-t1-ay22-23/train.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Nov-2022 20:40:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 18);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["ID", "Gender", "Age", "Height", "Weight", "family_history", "FCHCF", "FCV", "NMM", "CFBM", "Smoke", "CW", "CCM", "PAF", "TUT", "CA", "Transportation", "Obesity"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double", "categorical", "categorical", "double", "double", "categorical", "categorical", "double", "categorical", "double", "double", "categorical", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Gender", "family_history", "FCHCF", "CFBM", "Smoke", "CCM", "CA", "Transportation", "Obesity"], "EmptyFieldRule", "auto");

% Import the data
train = readtable(filename, opts);

end